- app/controllers/SummaryController.scala
Tax year warning message is displayed when a disposal date is not within a supported tax year
> Fixed tax year warning message on summary page

- app/views/whatNext/whatNext.scala.html
- conf/messages
- test/assets/MessageLookup.scala
- test/views/whatNext/WhatNextViewSpec.scala
https://docs.google.com/document/d/1E9hPqysCKvJHILrUDSKpXIZzKEUM5UfH_HnHFZTC6yQ/edit 
For reference
> Updated what next view to match new design.

- conf/messages
- test/assets/MessageLookup.scala
Updates only to disposal costs and rebased costs
> (Cgt 3210) - Making costs JO updates' messages consistent

- app/common/nonresident/TaxableGainCalculation.scala
- app/connectors/CalculatorConnector.scala
- app/constructors/PrivateResidenceReliefRequestConstructor.scala
- app/controllers/CalculationElectionController.scala
- app/controllers/CheckYourAnswersController.scala
- app/controllers/OtherReliefsController.scala
- app/controllers/OtherReliefsFlatController.scala
- app/controllers/OtherReliefsRebasedController.scala
- app/controllers/OtherReliefsTAController.scala
- app/controllers/PrivateResidenceReliefController.scala
- app/controllers/ReportController.scala
- app/controllers/SummaryController.scala
- test/common/TaxableGainCalculationSpec.scala
- test/connectors/CalculatorConnectorSpec.scala
- test/constructors/PrivateResidenceReliefRequestConstructorSpec.scala
- test/controllers/CalculationControllerTests/CalculationElectionActionSpec.scala
- test/controllers/CalculationControllerTests/CheckYourAnswersActionSpec.scala
- test/controllers/CalculationControllerTests/OtherReliefsActionSpec.scala
- test/controllers/CalculationControllerTests/OtherReliefsFlatActionSpec.scala
- test/controllers/CalculationControllerTests/OtherReliefsRebasedActionSpec.scala
- test/controllers/CalculationControllerTests/OtherReliefsTAActionSpec.scala
- test/controllers/CalculationControllerTests/PrivateResidenceReliefActionSpec.scala
- test/controllers/CalculationControllerTests/ReportActionSpec.scala
- test/controllers/CalculationControllerTests/SummaryActionSpec.scala
Also removed duplicated identical methods in various controllers
> Updated prr request constructor to include lived in property logic

- app/constructors/DeductionDetailsConstructor.scala
- app/constructors/PrivateResidenceReliefRequestConstructor.scala
- app/controllers/PrivateResidenceReliefController.scala
- app/forms/PrivateResidenceReliefForm.scala
- app/views/calculation/calculationElection.scala.html
- app/views/calculation/calculationElectionNoReliefs.scala.html
- app/views/calculation/privateResidenceRelief.scala.html
- app/views/helpers/calculationElectionHelperForm.scala.html
- app/views/helpers/expandableHelpTextHelper.scala.html
- app/views/helpers/formHiddenYesNoRadio.scala.html
- conf/messages
- public/stylesheets/cgt1.css
- test/assets/MessageLookup.scala
- test/constructors/DeductionDetailsConstructorSpec.scala
- test/constructors/PrivateResidenceReliefRequestConstructorSpec.scala
- test/controllers/CalculationControllerTests/PrivateResidenceReliefActionSpec.scala
- test/views/CalculationElectionNoReliefsViewSpec.scala
- test/views/PrivateResidenceReliefViewSpec.scala
- test/views/helpers/CalculationElectionHelperFormSpec.scala
Minor design tweaks discussed with and signed off by Brian and Jordan (e.g making text bold for the labels to be consistent with improvements, progressive disclosure instead of block form-hint, etc.) - some deviations from the prototype
> (Cgt 3289) Updates to PRR

- app/constructors/DeductionDetailsConstructor.scala
- test/constructors/DeductionDetailsConstructorSpec.scala
> (Cgt 3319) - Updated YourAnswersConstructor for PRR edgeDatesJustDaysBefore edge case

- project/MicroService.scala
- project/frontendBuild.scala
Updating cgt-calculator-non-resident-frontend to new build
> DL-1242 - Migrating to new build

- app/config/ApplicationConfig.scala
- app/config/CgtErrorHandler.scala
- app/config/frontendGlobal.scala
- app/config/frontendWiring.scala
- app/connectors/CalculatorConnector.scala
- app/constructors/OtherReliefsRequestConstructor.scala
- app/constructors/TotalGainRequestConstructor.scala
- app/controllers/CgtLanguageController.scala
- app/controllers/utils/package.scala
- app/views/calculation/howBecameOwner.scala.html
- app/views/calculation/otherProperties.scala.html
- app/views/calculation/previousLossOrGain.scala.html
- app/views/calculation/privateResidenceRelief.scala.html
- app/views/calculation/soldForLess.scala.html
- app/views/calculation/soldOrGivenAway.scala.html
- app/views/calculation/whoDidYouGiveItTo.scala.html
- app/views/helpers/formHiddenYesNoRadio.scala.html
- app/views/helpers/formYesNoRadio.scala.html
- project/frontendBuild.scala
- project/plugins.sbt
**Dependency uplift** (delete as appropriate)
* Uplifted dependencies for `cgt-calculator-non-resident-frontend`
> DL-1491 Uplifted dependencies

- project/frontendBuild.scala
- project/plugins.sbt
**Bug fix**
* Play upgrade to support security fix
> DL-1465 Play upgrade to support security fix

- app/config/ApplicationConfig.scala
- conf/application.conf
Dl-1647 - Conf changes for Get help form fix
Conf changes for Get help form fix
> Dl-1647 - Conf changes for Get help form fix

- project/AppDependencies.scala
This reverts commit a0c6584df10186c23ec843689be62973b2e6f632.
**Bug fix**
Reverting dependency updates to try and fix deployment issues
> DL-2411 Revert "Dependency updates"

- project/AppDependencies.scala
> DL-2411 revert mongo caching

- public/stylesheets/cgt.css
> DL-2904 - CGT - Accessibility Fixes

- app/common/TaxDates.scala
- app/constructors/DeductionDetailsConstructor.scala
- app/constructors/PrivateResidenceReliefRequestConstructor.scala
- app/controllers/PrivateResidenceReliefController.scala
- app/views/calculation/privateResidenceRelief.scala.html
- conf/messages.cy
- conf/messages.en
- test/assets/MessageLookup.scala
- test/util/PrivateResidenceReliefDateSpec.scala
- test/views/PrivateResidenceReliefViewSpec.scala
> CGT Tax Year Changes (Private residence relief)

- build.sbt
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
- []  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
> DL-3581 dependency updates

- app/config/ApplicationConfig.scala
- app/controllers/WhatNextController.scala
- app/models/DateModel.scala
- app/views/whatNext/whatNext.scala.html
- conf/application.conf
- project/AppDependencies.scala
- project/plugins.sbt
- test/controllers/CalculationControllerTests/WhatNextControllerSpec.scala
- test/views/whatNext/WhatNextViewSpec.scala
**New feature**
Code changes to reflect policy changes on reporting the capital gain tax for non-residents are applied.
> DL-3943 - Applied policy changes on reporting

- conf/application.conf
- project/AppDependencies.scala
> DL-4259 - A11y statement functionality for CGT-NR

- app/connectors/CalculatorConnector.scala
- conf/logback.xml
- test/controllers/CalculationControllerTests/SummaryActionSpec.scala
> DL-4440 Added xRequestId to header

- project/AppDependencies.scala
- test/constructors/FinalTaxAnswersRequestConstructorSpec.scala
- test/constructors/OtherReliefsRequestConstructorSpec.scala
- test/constructors/SalesDetailsConstructorSpec.scala
- test/controllers/CalculationControllerTests/AcquisitionCostsActionSpec.scala
- test/forms/AcquisitionValueFormSpec.scala
DL-4894 - removed unused dependencies and cleaned structure
hmrctests were not being used to removed it and cleaned up dependencies.
> DL-4894 - removed unused dependencies and cleaned structure

- app/common/Dates.scala
- app/views/calculation/checkYourAnswers.scala.html
- app/views/calculation/privateResidenceRelief.scala.html
- app/views/calculation/summaryReport.scala.html
- test/common/DatesSpec.scala
> DL-5109 - CGT: Summary page displays an incorrect year

- app/views/calculation/acquisitionValue.scala.html
- app/views/calculation/costsAtLegislationStart.scala.html
- build.sbt
- project/AppDependencies.scala
- project/plugins.sbt
> DL-5745 - Play 2.8 Update

- app/forms/DisposalDateForm.scala
- app/views/Layout.scala.html
- app/views/calculation/disposalDate.scala.html
- app/views/playComponents/errorSummary.scala.html
- app/views/playComponents/formInlineDateInput.scala.html
- app/views/playComponents/submitButton.scala.html
- conf/messages.cy
- conf/messages.en
- test/controllers/CalculationControllerTests/DisposalDateActionSpec.scala
- test/forms/DisposalDateFormSpec.scala
- test/views/DisposalDateViewSpec.scala
> DL-7427 disposal-date

- app/views/Layout.scala.html
- app/views/calculation/soldOrGivenAway.scala.html
- app/views/playComponents/input_radio.scala.html
- test/controllers/CalculationControllerTests/DisposalDateActionSpec.scala
- test/controllers/CalculationControllerTests/SoldOrGivenAwayActionSpec.scala
- test/views/DisposalDateViewSpec.scala
- test/views/SoldOrGivenAwayViewSpec.scala
> DL-7428 - soldOrGivenAway

- app/views/calculation/soldForLess.scala.html
- app/views/playComponents/input_yes_no.scala.html
- test/controllers/CalculationControllerTests/SoldForLessActionSpec.scala
- test/views/SoldForLessViewSpec.scala
> DL-7429 soldForLess.scala.html

- app/views/calculation/boughtForLess.scala.html
- test/controllers/CalculationControllerTests/BoughtForLessActionSpec.scala
- test/views/BoughtForLessViewSpec.scala
> DL-7434 boughtForLess page

- app/views/Layout.scala.html
- app/views/calculation/howBecameOwner.scala.html
- conf/application.conf
- test/controllers/CalculationControllerTests/HowBecameOwnerActionSpec.scala
- test/views/HowBecameOwnerViewSpec.scala
added `HmrcReportTechnicalIssueHelper`
> DL-7433 - howBecameOwner

- app/forms/AcquisitionDateForm.scala
- app/views/calculation/acquisitionDate.scala.html
- test/controllers/CalculationControllerTests/AcquisitionDateActionSpec.scala
- test/forms/AcquisitionDateFormSpec.scala
- test/views/AcquisitionDateViewSpec.scala
> DL-7432 acquisition-date

- app/views/calculation/whoDidYouGiveItTo.scala.html
- test/views/WhoDidYouGiveItToViewSpec.scala
> DL-7443 - whoDidYouGiveItTo

- app/views/calculation/noTaxToPay.scala.html
- test/controllers/CalculationControllerTests/WhoDidYouGiveItToControllerSpec.scala
- test/views/NoTaxToPayViewSpec.scala
> DL-7444 no-tax-to-pay

- app/views/calculation/worthWhenGiftedTo.scala.html
- test/controllers/CalculationControllerTests/WorthWhenGiftedToActionSpec.scala
- test/views/WorthWhenGiftedToViewSpec.scala
> DL-7437 worthWhenGiftedTo.scala.html

- app/views/calculation/worthWhenInherited.scala.html
- test/controllers/CalculationControllerTests/WorthWhenInheritedActionSpec.scala
- test/views/WorthWhenInheritedViewSpec.scala
> DL-7436 - worthWhenInherited

- app/views/playComponents/expandableHelpTextHelper.scala.html
- app/views/whatNext/whatNext.scala.html
- test/assets/MessageLookup.scala
- test/controllers/CalculationControllerTests/WhatNextControllerSpec.scala
- test/views/whatNext/WhatNextViewSpec.scala
> DL-7448 what-next

- app/views/calculation/acquisitionCosts.scala.html
- test/controllers/CalculationControllerTests/AcquisitionCostsActionSpec.scala
- test/views/AcquisitionCostsViewSpec.scala
> DL-7438 acquisitionCosts.scala.html

- app/views/Layout.scala.html
- app/views/calculation/disposalDate.scala.html
- app/views/playComponents/button_link.scala.html
- app/views/warnings/sessionTimeout.scala.html
- test/controllers/TimeoutControllerSpec.scala
> DL-7449 - session-timeout

- app/views/calculation/rebasedValue.scala.html
- test/views/RebasedValueViewSpec.scala
> DL-7441 rebasedValue.scala.html

- app/views/calculation/worthWhenBoughtForLess.scala.html
- test/assets/MessageLookup.scala
- test/controllers/CalculationControllerTests/WorthWhenBoughtForLessActionSpec.scala
- test/views/WorthWhenBoughtForLessViewSpec.scala
> DL-7435 worthWhenBoughtForLess.scala

- app/views/calculation/acquisitionValue.scala.html
- test/controllers/CalculationControllerTests/AcquisitionValueActionSpec.scala
- test/views/AcquisitionValueViewSpec.scala
> DL-7450 acquisitionValue.scala

- app/views/calculation/calculationElection.scala.html
- app/views/playComponents/calculationElectionHelperForm.scala.html
- test/controllers/CalculationControllerTests/CalculationElectionActionSpec.scala
- test/views/CalculationElectionViewSpec.scala
> DL-7446 - calculationElection

- app/views/calculation/claimingReliefs.scala.html
- test/controllers/CalculationControllerTests/ClaimingReliefsActionSpec.scala
- test/views/ClaimingReliefsViewSpec.scala
> DL-7454 claiming-reliefs view

- app/views/Layout.scala.html
- app/views/calculation/summary.scala.html
- app/views/playComponents/summaryNumericRow.scala.html
- app/views/playComponents/summaryPartial.scala.html
- app/views/playComponents/summaryPartialDeductionsSection.scala.html
- app/views/playComponents/summaryPartialTaxToPay.scala.html
- app/views/playComponents/summaryPartialTaxableGain.scala.html
- app/views/playComponents/summaryPartialWorkingOutSection.scala.html
- test/assets/MessageLookup.scala
- test/controllers/CalculationControllerTests/SummaryActionSpec.scala
- test/views/SummaryViewSpec.scala
> DL-7447 summary

- app/controllers/CurrentIncomeController.scala
- app/views/calculation/currentIncome.scala.html
- test/controllers/CalculationControllerTests/CurrentIncomeActionSpec.scala
- test/views/CurrentIncomeViewSpec.scala
> DL-7456 - currentIncome

- app/views/calculation/disposalValue.scala.html
- app/views/playComponents/formInputMoney.scala.html
- test/controllers/CalculationControllerTests/DisposalValueActionSpec.scala
- test/views/DisposalValueViewSpec.scala
Added optional hint text to `formInputMoney`
> DL-7457 - disposalValue

- app/views/calculation/acquisitionDate.scala.html
- app/views/calculation/costsAtLegislationStart.scala.html
- app/views/playComponents/errorSummary.scala.html
- test/assets/MessageLookup.scala
- test/controllers/CalculationControllerTests/CostsAtLegislationStartActionSpec.scala
- test/views/CostsAtLegislationStartViewSpec.scala
> DL-7455 costs-at-legislation-start

- app/views/calculation/howMuchGain.scala.html
- test/controllers/CalculationControllerTests/HowMuchGainActionSpec.scala
- test/views/HowMuchGainViewSpec.scala
> DL-7458 howMuchGain.scala.html

- app/views/calculation/marketValueGaveAway.scala.html
- test/controllers/CalculationControllerTests/MarketValueWhenSoldOrGaveAwayActionSpec.scala
- test/views/MarketValueGaveAwayViewSpec.scala
> DL-7460 marketValueGaveAway.scala

- app/views/calculation/howMuchLoss.scala.html
- test/controllers/CalculationControllerTests/HowMuchLossActionSpec.scala
- test/views/HowMuchLossViewSpec.scala
> DL-7459 howMuchLoss.scala.html

- app/views/calculation/broughtForwardLosses.scala.html
- app/views/playComponents/formHiddenYesNoRadioCurrencyInput.scala.html
- test/controllers/CalculationControllerTests/BroughtForwardLossesActionSpec.scala
- test/views/BroughtForwardLossesViewSpec.scala
> DL-7452 broughtForwardLosses.scala.html

- app/views/calculation/otherProperties.scala.html
- test/controllers/CalculationControllerTests/OtherPropertiesActionSpec.scala
- test/views/OtherPropertiesViewSpec.scala
> DL-7462 other-properties

- app/views/calculation/noCapitalGainsTax.scala.html
- test/controllers/CalculationControllerTests/NoCapitalGainsTaxActionSpec.scala
- test/views/NoCapitalGainsTaxViewSpec.scala
> DL-7461 noCapitalGainsTax.scala

- app/views/calculation/improvements.scala.html
- app/views/playComponents/formHiddenYesNoRadioCurrencyInput.scala.html
- app/views/playComponents/govukDetails.scala.html
- test/controllers/CalculationControllerTests/ImprovementsActionSpec.scala
- test/views/ImprovementsViewSpec.scala
> DL-7439 improvements

- app/views/calculation/outsideTaxYear.scala.html
- test/controllers/CalculationControllerTests/OutsideTaxYearActionSpec.scala
- test/views/OutsideTaxYearViewSpec.scala
> DL-7467 outsideTaxYear.scala.html

- app/views/calculation/otherReliefsFlat.scala.html
- test/controllers/CalculationControllerTests/OtherReliefsFlatActionSpec.scala
- test/views/OtherReliefsFlatViewSpec.scala
> DL-7464 otherReliefsFlat.scala

- app/views/calculation/worthBeforeLegislationStart.scala.html
- test/assets/MessageLookup.scala
- test/controllers/CalculationControllerTests/WorthBeforeLegislationStartActionSpec.scala
- test/views/WorthBeforeLegislationStartViewSpec.scala
> DL-7473 worthBeforeLegislationStart

- app/views/calculation/otherReliefsTA.scala.html
- test/controllers/CalculationControllerTests/OtherReliefsTAActionSpec.scala
- test/views/OtherReliefsTAViewSpec.scala
> DL-7466 otherReliefsTA.scala.html

- app/views/calculation/personalAllowance.scala.html
- test/controllers/CalculationControllerTests/PersonalAllowanceActionSpec.scala
- test/views/PersonalAllowanceViewSpec.scala
> DL-7468 personalAllowance.scala.html

- app/views/calculation/privateResidenceRelief.scala.html
- app/views/playComponents/formHiddenYesNoRadioCurrencyInput.scala.html
- test/assets/MessageLookup.scala
- test/controllers/CalculationControllerTests/PrivateResidenceReliefActionSpec.scala
- test/views/PrivateResidenceReliefViewSpec.scala
> DL-7470 private-residence-relief

- app/views/calculation/propertyLivedIn.scala.html
- test/controllers/CalculationControllerTests/PropertyLivedInActionSpec.scala
- test/views/PropertyLivedInViewSpec.scala
> DL-7471 propertyLivedIn.scala

- app/views/calculation/previousLossOrGain.scala.html
- test/assets/MessageLookup.scala
- test/controllers/CalculationControllerTests/PreviousGainOrLossActionSpec.scala
- test/views/PreviousLossOrGainViewSpec.scala
> DL-7469 previousLossOrGain.scala.html

- app/views/Layout.scala.html
- app/views/calculation/disposalDate.scala.html
- app/views/calculation/noCapitalGainsTax.scala.html
- app/views/calculation/noTaxToPay.scala.html
- app/views/calculation/otherReliefsFlat.scala.html
- app/views/calculation/outsideTaxYear.scala.html
- app/views/calculation/privateResidenceRelief.scala.html
> DL-7633 Code clean up

- conf/application.conf
- conf/messages.cy
- project/AppDependencies.scala
Updated Bootstrap-play to 5.19.0, which contains the global error messages.
> DL-7715 - Added Welsh for error pages

- app/views/calculation/outsideTaxYear.scala.html
- app/views/playComponents/formHiddenYesNoRadioCurrencyInput.scala.html
> DL-7632 Updates for consistency

- app/views/calculation/acquisitionCosts.scala.html
- app/views/calculation/acquisitionDate.scala.html
- app/views/calculation/broughtForwardLosses.scala.html
- app/views/calculation/currentIncome.scala.html
- app/views/calculation/disposalCosts.scala.html
- app/views/calculation/improvements.scala.html
- app/views/calculation/marketValueSold.scala.html
- app/views/calculation/personalAllowance.scala.html
- app/views/calculation/previousLossOrGain.scala.html
- app/views/calculation/rebasedValue.scala.html
- app/views/calculation/worthBeforeLegislationStart.scala.html
- app/views/calculation/worthWhenBoughtForLess.scala.html
- test/views/BroughtForwardLossesViewSpec.scala
- test/views/CurrentIncomeViewSpec.scala
- test/views/DisposalCostsViewSpec.scala
- test/views/ImprovementsViewSpec.scala
- test/views/MarketValueWhenSoldViewSpec.scala
- test/views/OutsideTaxYearViewSpec.scala
- test/views/RebasedValueViewSpec.scala
- test/views/WorthBeforeLegislationStartViewSpec.scala
- test/views/WorthWhenBoughtForLessViewSpec.scala
> DL-7782 Hint text changes

- app/views/calculation/broughtForwardLosses.scala.html
- test/views/BroughtForwardLossesViewSpec.scala
> DL-7825 - Remove gap

- app/assets/stylesheets/cgt-calculator-non-resident.css
- app/views/Layout.scala.html
- app/views/calculation/checkYourAnswers.scala.html
- test/views/LayoutViewSpec.scala
> DL-7826 - improvements to check-your-answers page

- app/views/calculation/otherReliefs.scala.html
- test/controllers/CalculationControllerTests/OtherReliefsActionSpec.scala
- test/views/OtherReliefsViewSpec.scala
> DL-7827 otherReliefs.scala content changes

- project/AppDependencies.scala
> DL-9032 - removed unused dependency

- conf/messages.cy
> DL-9177: Update welsh

- app/views/playComponents/language_selection.scala.html
- build.sbt
- project/AppDependencies.scala
- project/plugins.sbt
- test/common/CommonPlaySpec.scala
> DL-10007 Java11 dependencies upgrade

- app/views/calculation/summary.scala.html
ATs for DL-9854 used `.govuk-button` to select continue button, changed to `#continue-button`.
> DL-9854 - Added continue button IDs

- README.md
> DL-9897 Update README.md

- app/views/calculation/privateResidenceRelief.scala.html
- app/views/calculation/propertyLivedIn.scala.html
- app/views/playComponents/formHiddenYesNoRadioCurrencyInput.scala.html
- test/views/PropertyLivedInViewSpec.scala
> DL-11968 fix h1 in legend text

- app/views/calculation/marketValueGaveAway.scala.html
- app/views/calculation/worthWhenGiftedTo.scala.html
- test/assets/MessageLookup.scala
- test/views/MarketValueGaveAwayViewSpec.scala
- test/views/WorthWhenGiftedToViewSpec.scala
> DL-11974 change hint to para

- app/config/ApplicationConfig.scala
- app/views/Layout.scala.html
- build.sbt
> DL-11942 - switched to hmrcStandardPage

- app/views/whatNext/whatNext.scala.html
- conf/application.conf
> DL-11942 - added govuk-body to hyperlink

- conf/messages.cy
- conf/messages.en
- project/AppDependencies.scala
- test/assets/MessageLookup.scala
> DL-11972 brought-forward-losses content update

- app/views/calculation/summary.scala.html
- app/views/calculation/summaryReport.scala.html
- test/assets/MessageLookup.scala
- test/common/DatesSpec.scala
- test/constructors/AnswersConstructorSpec.scala
- test/controllers/CalculationControllerTests/RebasedValueActionSpec.scala
- test/controllers/CalculationControllerTests/SummaryActionSpec.scala
- test/forms/MarketValueDisposalFormSpec.scala
- test/forms/PreviousLossOrGainFormSpec.scala
- test/forms/RebasedValueFormSpec.scala
- test/views/PreviousLossOrGainViewSpec.scala
- test/views/SummaryViewSpec.scala
> DL-12078 updated title on summary page

- app/forms/BroughtForwardLossesForm.scala
- test/forms/BroughtForwardLossesFormSpec.scala
> [DLS-9366] Fix error styling

- app/views/playComponents/summaryPartial.scala.html
- test/views/SummaryViewSpec.scala
- test/views/playComponents/SummaryPartialViewSpec.scala
https://jira.tools.tax.service.gov.uk/browse/DLS-9375
> DLS-9375 update summary heading

- project/AppDependencies.scala
**Maintenance** (delete as appropriate)
> [DLS-10008] Tudor Crown update

- app/views/playComponents/summaryPartial.scala.html
- app/views/playComponents/summaryPartialDeductionsSection.scala.html
- app/views/playComponents/summaryPartialTaxToPay.scala.html
- app/views/playComponents/summaryPartialTaxableGain.scala.html
- app/views/playComponents/summaryPartialWorkingOutSection.scala.html
- test/views/playComponents/SummaryPartialTaxToPayViewSpec.scala
> DLS-9376 - Added captions and moved h2

- app/views/playComponents/summaryPartialTaxToPay.scala.html
> DLS-9376 - Added captions and moved h2 - quick fix

- app/config/CgtErrorHandler.scala
- app/constructors/AnswersConstructor.scala
- app/controllers/utils/package.scala
- project/AppDependencies.scala
- test/config/CgtErrorHandlerSpec.scala
- test/constructors/AnswersConstructorSpec.scala
- test/controllers/utils/RecoverableFutureSpec.scala
Custom Exception and handler is added.
> DLS-10584 Exception related to current income field

- app/assets/stylesheets/cgt-calculator-non-resident.css
- app/views/calculation/checkYourAnswers.scala.html
- project/AppDependencies.scala
> DLS-11793 CYA page UCD recommended changes
